name: Keep Render Backend Alive

on:
  schedule:
    # Run every 14 minutes (Render sleeps after 15 mins)
    - cron: '*/14 * * * *'
  workflow_dispatch: # Allows you to run this manually from GitHub if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        # We use -I to just fetch the headers (lighter/faster)
        run: curl -I https://habit-tracker-2-12x6.onrender.com
